### ISSUE TITLE
blogデータの移行

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-org#8]
現行の tdiary.org からmongolab へデータをインポートする。インポートにはbin/tdiary-mongodb-convertを使う。

 * 参考: [Heroku上のtDiaryへデータを移行する](http://sho.tdiary.net/20150206.html#p01)
 * -sの引数でスタイルディレクトリを指定しないと動かないので注意

コマンド

```
$ bundle exec bin/tdiary-mongodb-convert -s ../tdiary-org/lib/tdiary/style -m $MONGODB_URL ../tdiary-org/data
```

## 問題1: bin/tdiary-mongodb-convertが起動しない

```
$ bundle exec bin/tdiary-mongodb-convert -s ../tdiary-org/lib/tdiary/style -m $MONGODB_URL ../tdiary-org/data
bundler: failed to load command: bin/tdiary-mongodb-convert (bin/tdiary-mongodb-convert)
LoadError: cannot load such file -- emot
  /Users/machu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/tdiary-core-fa905e345655/lib/tdiary/core_ext.rb:1:in `require'
  /Users/machu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/tdiary-core-fa905e345655/lib/tdiary/core_ext.rb:1:in `<top (required)>'
  bin/tdiary-mongodb-convert:13:in `require'
  bin/tdiary-mongodb-convert:13:in `<top (required)>'
```

### 原因

tdiaryをgemで読み込んだ場合に、依存関係のあるemotが読み込まれない。

### 対策

Gemfileに `gem ‘emot'` を追記。

## 問題2: blog.rbの読み込みに失敗

```
$ bundle exec bin/tdiary-mongodb-convert -s ../tdiary-org/lib/tdiary/style -m $MONGODB_URL ../tdiary-org/data
bundler: failed to load command: bin/tdiary-mongodb-convert (bin/tdiary-mongodb-convert)
NameError: undefined method `eval_rhtml' for class `TDiary::TDiaryForm'
  /Users/machu/src/github.com/tdiary/tdiary-org/lib/tdiary/style/blog.rb:84:in `<class:TDiaryForm>'
  /Users/machu/src/github.com/tdiary/tdiary-org/lib/tdiary/style/blog.rb:83:in `<module:TDiary>'
  /Users/machu/src/github.com/tdiary/tdiary-org/lib/tdiary/style/blog.rb:18:in `<top (required)>'
  /Users/machu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/tdiary-core-fa905e345655/lib/tdiary/io/base.rb:46:in `require'
```

### 原因

lib/tdiary/admin.rbで定義されている`TDiary::TDiaryForm`が読み込まれていないため。

### 対策

lib/tdiary/style/blog.rbの先頭でtdiary/adminを読み込む。

```
begin
    require 'tdiary'
    require 'tdiary/admin'
    require 'tdiary/style/tdiary'
rescue LoadError
    require 'tdiary/tdiary_style'
end
```

## 問題3: blogrd.rbの読み込みに失敗

```
$ bundle exec bin/tdiary-mongodb-convert -s ../tdiary-org/lib/tdiary/style -m $MONGODB_URL ../tdiary-org/data
bundler: failed to load command: bin/tdiary-mongodb-convert (bin/tdiary-mongodb-convert)
LoadError: cannot load such file -- tdiary/rd_style
  /Users/machu/src/github.com/tdiary/tdiary-core/lib/tdiary/style/blogrd.rb:25:in `require'
  /Users/machu/src/github.com/tdiary/tdiary-core/lib/tdiary/style/blogrd.rb:25:in `rescue in <top (required)>'
  /Users/machu/src/github.com/tdiary/tdiary-core/lib/tdiary/style/blogrd.rb:22:in `<top (required)>'
  /Users/machu/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/tdiary-core-fa905e345655/lib/tdiary/io/base.rb:46:in `require'
```

### 原因

rdスタイルが読み込まれていない。

### 対策

Gemfileに `gem 'tdiary-style-rd'` を追記。

**Comment by tdtds** [comment]
これ、問題1と2は元の方へフィードバックした方がいい感じかな? (3はio-mongodbのドキュメントで注意を促すべきかも知れない)

**Comment by machu** [comment]
はい。フィードバックしておきますね。終わったらこのissueをクローズします。
